// RootLayout.tsx
import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Agregamos Tailwind CSS */}
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" />
      </head>
      <body className="font-sans">
        {/* Header */}
        <header className="bg-gray-800 text-white py-4">
          <nav className="container mx-auto flex justify-between items-center">
            <ul className="flex">
              <li className="mr-6"><a href="/" className="hover:text-blue-500">Inicio</a></li>
              <li className="mr-6"><a href="/about" className="hover:text-blue-500">Acerca de</a></li>
              <li><a href="/contact" className="hover:text-blue-500">Contacto</a></li>
            </ul>
            <a href="/nombre" className="text-white hover:text-blue-500">Vanegas Bernal Angel Guillermo</a>
          </nav>
        </header>

        {/* Contenido de las páginas */}
        {children}

        {/* Footer */}
        <footer className="bg-gray-800 text-white py-4 mt-8">
          <p className="text-center">&copy; 2024 Tu Sitio Web</p>
        </footer>
      </body>
    </html>
  );
}
